### ISSUE TITLE
NameError for imported module

### ISSUE THREAD

**Issue by TaiSakuma** [simonsobs/nextline#7]
This script doesn't work.

```python
import time
def f():
    time.sleep(1.0)
f()
```

It raises `NameError: name 'time' is not defined`

It works if import within the function.

```python
def f():
    import time
    time.sleep(1.0)
f()
```

Even this works.

```python
import time
time.sleep(1.0)
```

**Comment by TaiSakuma** [comment]
a minimal script to reproduce the error

```python
❯ cat ./s.py 
statement = """
import time
def f():
    time.sleep(1.0)
f()
"""

code = compile(statement, '<string>', 'exec')

def e():
    exec(code)

e()
```

```python
❯ python ./s.py 
Traceback (most recent call last):
  File "./s.py", line 13, in <module>
    e()
  File "./s.py", line 11, in e
    exec(code)
  File "<string>", line 5, in <module>
  File "<string>", line 4, in f
NameError: name 'time' is not defined
```

**Comment by TaiSakuma** [comment]
It works with options of [`exec()`](https://docs.python.org/3/library/functions.html#exec)

```python
❯ cat ./s.py 
statement = """
import time
def f():
    time.sleep(1.0)
f()
"""

code = compile(statement, '<string>', 'exec')

def e():
    exec(code, globals(), globals())

e()
```

```python
❯ python ./s.py
❯ 
```

**Comment by TaiSakuma** [comment]
The third argument seems to be redundant if it would be the same as the second.  So it can be written as `exec(code, globals())`.

> If only globals is provided, it must be a dictionary (and not a subclass of dictionary), **which will be used for both the global and the local variables.**

https://docs.python.org/3/library/functions.html#exec

**Comment by TaiSakuma** [comment]
resolved with the commit https://github.com/simonsobs/nextline/commit/55765d686480750a5c3090dbfffbbb1ad3f34780

**Comment by TaiSakuma** [comment]
updated with https://github.com/simonsobs/nextline/commit/94741b85002008cd84b7094a622ff03d18ecef5c, giving `{'__name__': __name__}`  instead of `globals()`.

**Comment by TaiSakuma** [comment]
This commit fc862ead4242e7cbb99c05542c6dbf4a88196565 adds a test that should fail if this issue occurs again.

https://github.com/simonsobs/nextline/blob/fc862ead4242e7cbb99c05542c6dbf4a88196565/tests/test_wrap.py#L34-L48
